baseurl = "http://localhost"
title = "daanhorn.nl"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Code released under the Apache 2.0 license."

[author]
  name = "Daan Horn"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Software Engineering Blog"
  Author = "Daan Horn"
  email = "daanhornnl@gmail.com"
  Ganalytics = "XX-00000000-0"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/horndaan"
[[params.social]]
  title = "github"
  url = "https://github.com/daanhorn"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -190
[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = -180
[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = -180
